export const movies = [
	{ id: 1, title: "Dune: Parte Dos", genre: "Ciencia ficción", year: 2024, rating: 8.8, description: "Paul Atreides se une a Chani y a los fremen mientras busca venganza y enfrenta su destino en Arrakis.", image: "https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg" },
	{ id: 2, title: "Pobres criaturas", genre: "Fantasía", year: 2023, rating: 8.0, description: "Bella Baxter explora el mundo con una curiosidad libre y una mirada completamente nueva sobre la vida.", image: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg" },
	{ id: 3, title: "Oppenheimer", genre: "Drama", year: 2023, rating: 8.6, description: "La historia del científico que lideró el proyecto que cambió para siempre la historia moderna.", image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg" },
	{ id: 4, title: "El menú", genre: "Suspenso", year: 2022, rating: 7.2, description: "Una pareja visita un exclusivo restaurante en una isla remota donde la cena toma un giro inesperado.", image: "https://image.tmdb.org/t/p/w500/v31MsWhF9WFh7QvZ6m9jQ8GqQ9d.jpg" },
	{ id: 5, title: "Spider-Man: Cruzando el multiverso", genre: "Animación", year: 2023, rating: 8.6, description: "Miles Morales viaja por distintas dimensiones y descubre que ser Spider-Man puede tener muchas formas.", image: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg" },
	{ id: 6, title: "Godzilla Minus One", genre: "Acción", year: 2023, rating: 8.3, description: "En el Japón de la posguerra, una nueva amenaza obliga a un país a recuperar su valor.", image: "https://image.tmdb.org/t/p/w500/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg" },
	{ id: 7, title: "Anatomía de una caída", genre: "Drama", year: 2023, rating: 7.7, description: "Un juicio intenta descubrir la verdad sobre la muerte de un hombre y pone en duda a todos.", image: "https://image.tmdb.org/t/p/w500/k7h5WABq2TgNQ5pJ8Ww9n7s0JqK.jpg" },
	{ id: 8, title: "La zona de interés", genre: "Historia", year: 2023, rating: 7.3, description: "Una familia intenta construir una vida ideal junto a un lugar que esconde una realidad imposible de ignorar.", image: "https://image.tmdb.org/t/p/w500/hUu9zyZmBb4q9Y5fP5oA6M8m4K.jpg" },
]